name: handson-ml
dependencies:
  - python=3.8
  - scikit-learn
  - matplotlib
  - jupyter
  - pandas
  - pillow
  - nltk
  - pip:
    - tensorflow-gpu
    - gym
    - graphviz
    - watermark
    - urlextract
    - xgboost